// <auto-generated />
namespace BITCollege_RS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rsass_college_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rsass_college_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202202172252168_rsass_college_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
