// <auto-generated />
namespace BITCollege_RS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class configuredthings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(configuredthings));
        
        string IMigrationMetadata.Id
        {
            get { return "202202180540251_configured-things"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
